/*
 * ExerciseThumbnail.java
 *
 * Created on January 4, 2009, 5:50 PM
 */

package org.laukvik.trainer.exercise;

import java.awt.Dimension;

import javax.swing.ImageIcon;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

/**
 *
 * @author  morten
 */
public class ExerciseThumbnail extends javax.swing.JPanel {
    
    private static final long serialVersionUID = 1L;
    public final static Dimension size = new Dimension( 150, 180 );
    private final ExercisePhoto photo;
    
    /** Creates new form ExerciseThumbnail */
    public ExerciseThumbnail( final ExercisePhoto photo ) {
        this.photo = photo;
        setMaximumSize( size );
        setMinimumSize( size );
        setSize( size );
        initComponents();

        
    	commentsTextArea.addCaretListener( new CaretListener(){
            public void caretUpdate(CaretEvent evt) {
                  photo.setComments( commentsTextArea.getText()  );
            }}
    	);


    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        viewDialog = new javax.swing.JDialog();
        viewScrollPane = new javax.swing.JScrollPane();
        viewLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        copyrightLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        commentsScrollPane = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();

        viewDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        viewDialog.setTitle("Trainer");
        viewDialog.setAlwaysOnTop(true);
        viewDialog.setModal(true);
        viewScrollPane.setBorder(null);
        viewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewLabel.setIcon(new ImageIcon( org.laukvik.trainer.journal.JournalManager.getExercisePhotoFile( photo ).getAbsolutePath() ));
        viewScrollPane.setViewportView(viewLabel);

        viewDialog.getContentPane().add(viewScrollPane, java.awt.BorderLayout.CENTER);

        jPanel1.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(photo.getComments());
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Description");

        jLabel2.setText("Copyright");

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText(photo.getCopyright());
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jScrollPane2.setViewportView(jTextArea2);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewDialog.getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(150, 180));
        setMinimumSize(new java.awt.Dimension(150, 180));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        copyrightLabel.setBackground(new java.awt.Color(204, 204, 204));
        copyrightLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        copyrightLabel.setForeground(new java.awt.Color(153, 153, 153));
        copyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLabel.setText(photo.getCopyright());

        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLabel.setIcon(new ImageIcon( org.laukvik.trainer.journal.JournalManager.getExerciseThumbnailFile( photo ).getAbsolutePath() ));
        iconLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        iconLabel.setMinimumSize(new java.awt.Dimension(100, 100));

        commentsScrollPane.setBorder(null);
        commentsTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        commentsTextArea.setColumns(20);
        commentsTextArea.setLineWrap(true);
        commentsTextArea.setRows(5);
        commentsTextArea.setText(photo.getComments());
        commentsTextArea.setWrapStyleWord(true);
        commentsTextArea.setBorder(null);
        commentsScrollPane.setViewportView(commentsTextArea);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(copyrightLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(iconLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(commentsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(commentsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .add(iconLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(copyrightLabel)
                .add(34, 34, 34))
        );
    }// </editor-fold>                        

    private void formMouseClicked(java.awt.event.MouseEvent evt) {                                  
        ImageIcon icon = (ImageIcon) viewLabel.getIcon();
        icon.getImage();
        
//        viewDialog.setSize( 100, 100 );
//        int heightStart  = viewScrollPane.getHeight();
//        int heightFinish = viewScrollPane.getHeight();
        
//        System.out.println( "Start: " + heightStart + " Finish: " + heightFinish );
        
//        Dimension size = new Dimension( icon.getIconWidth()+jPanel1.getWidth(), icon.getIconHeight() + heightStart );
        Dimension size = new Dimension( 700, 500 );
//        System.out.println( size.getWidth() + "x" + size.getHeight() );
        

        
//        
        viewDialog.setSize( size );
        viewDialog.setMinimumSize( size );
        viewDialog.setPreferredSize( size );
        viewDialog.setLocationRelativeTo( this.getRootPane() );
        viewDialog.setVisible( true );
    }                                 
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane commentsScrollPane;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JDialog viewDialog;
    private javax.swing.JLabel viewLabel;
    private javax.swing.JScrollPane viewScrollPane;
    // End of variables declaration                   
    
}
